openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/mailings/:
    get:
      operationId: listMailings
      description: Statistics for all mailings
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mailing'
          description: ''
      tags:
      - api
    post:
      operationId: createMailing
      description: Create new mailing and run/schedule task
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mailing'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Mailing'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Mailing'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mailing'
          description: ''
      tags:
      - api
  /api/v1/mailings/{id}/:
    get:
      operationId: retrieveMailing
      description: Statistics for one mailing
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this mailing.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mailing'
          description: ''
      tags:
      - api
    put:
      operationId: updateMailing
      description: Change existing mailing
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this mailing.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mailing'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Mailing'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Mailing'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mailing'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateMailing
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this mailing.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mailing'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Mailing'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Mailing'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mailing'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyMailing
      description: Delete existing mailing
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this mailing.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/v1/clients/:
    post:
      operationId: createClient
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Client'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
          description: ''
      tags:
      - api
  /api/v1/clients/{id}/:
    put:
      operationId: updateClient
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this client.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Client'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateClient
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this client.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Client'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyClient
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this client.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Mailing:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        start_time:
          type: string
          format: date-time
        text:
          type: string
        client_operator_code_filter:
          type: string
          nullable: true
          maxLength: 10
        client_tag_filter:
          type: string
          nullable: true
          maxLength: 50
        end_time:
          type: string
          format: date-time
      required:
      - start_time
      - text
      - end_time
    Client:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        phone:
          type: string
          maxLength: 11
        operator_code:
          type: string
          maxLength: 10
        tag:
          type: string
          nullable: true
          maxLength: 50
        timezone:
          type: string
          maxLength: 10
      required:
      - phone
      - operator_code
      - timezone
